version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Packaging Lambda function"
      - zip -r lambda_function.zip lambda_function.py

  post_build:
    commands:
      - echo "Deploying Lambda"
      - aws lambda update-function-code \
        --function-name image-resizer \
        --zip-file fileb://lambda_function.zip
