version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update -y
      - apt-get install zip -y

  build:
    commands:
      - echo "Packaging Lambda function"
      - zip -r lambda_function.zip lambda_function.py
      - ls -l

  post_build:
    commands:
      - echo "Deploying Lambda"
      - aws lambda update-function-code \
        --function-name get-processed-image \
        --zip-file fileb://lambda_function.zip \
        --region ap-south-1
